### ISSUE TITLE
Website frontpage

### ISSUE THREAD

**Issue by alexzhang1618** [acmucsd/hack-website#7]
- Design and implement a website frontpage
- Should look cool and introduce visitors to what ACM Hack is and things they should get started with looking at
- List upcoming hack events using portal API?

**Comment by nishantbalaji** [comment]
A design has already been created: 
https://www.figma.com/file/I3BAtxQgaPwHCylOqaT29e/Community-Site-Templates?type=design&node-id=1%3A128&mode=design&t=7u01OqCEvEwxoagA-1

![image](https://github.com/acmucsd/hack-website/assets/44332326/8bb42b38-5046-4c9c-a1c2-f670694ca79e)

**Comment by nik-dange** [comment]
Re-organized this issue already
